defmodule Textexp.SqliteRepo.Migrations.AddDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`, then
  edited: `writings` is recreated (its previous rows, keyed by `doc_name`, are
  dropped) because SQLite cannot add a NOT NULL foreign key to a populated table.
  """

  use Ecto.Migration

  def up do
    create table(:documents, primary_key: false) do
      add :owner_id, references(:users, column: :id, name: "documents_owner_id_fkey", type: :uuid)
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :snapshot, :binary
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end

    drop table(:writings)

    create table(:writings, primary_key: false) do
      add :document_id,
          references(:documents, column: :id, name: "writings_document_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :binary, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:writings)
    drop table(:documents)

    create table(:writings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :doc_name, :text, null: false
      add :version, :text
      add :value, :binary, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end
end
